APEXCORE-505 Heartbeat loop was blocked waiting for operator activati…
apache/apex-core pull request #405
Opened 2016-10-05 02:10 UTC by sandeshh

…on, the reason for this is that Stream activation(Only BufferServerSubscriber and WindowGenerator) waits for operator activation in a heartbeat thread. There is no need to have this synchronization, as Tuples are pulled from the queues by the operators.

@vrozov @tweise please review

2016-10-19 00:14 UTC, vrozov reviewed
Please add a unit test that checks that it is OK to activate BufferServerSubscriber before an operator that consumes from the reservoir.

2016-10-24 23:32 UTC, sandeshh commented
@vrozov I have added the unit test. Please review.

2016-10-25 00:33 UTC, vrozov commented
Please avoid code duplication.

2016-10-25 00:36 UTC, vrozov commented
It is necessary to test operator activation sequence.

2016-11-03 18:50 UTC, vrozov requested changes

2016-11-03 18:50 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    int bufferServerPort = 0;
delay this declaration till it can be initialized

2016-11-03 18:50 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    Server bufferServer = null;
delay declaration till it can be initialized

2016-11-03 18:50 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    bufferServerPort = bindAddr.getPort();
final int bufferServerPort = bufferServer.run(eventloop).getPort();

2016-11-03 18:50 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    final GenericNode gn = new GenericNode(go, new com.datatorrent.stram.engine.OperatorContext(0, "operator",
Please check if OperatorContext is required or it can be null

2016-11-03 18:50 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    issContext.setBufferServerAddress(InetSocketAddress.createUnresolved("localhost", bufferServerPort));
Why createUnresolved?

2016-11-03 18:50 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    oss.put(est);
The purpose of the test is to check that BufferServerSubscriber can be activated and process tuples without a loss even if it is activated before the operator is setup and starts processing tuples. There is no guarantee that Publisher actually delivers tuples to the buffer server and buffer server sends them to the Subscriber in the test.

2016-11-05 03:35 UTC, sandeshh commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    final GenericNode gn = new GenericNode(go, new com.datatorrent.stram.engine.OperatorContext(0, "operator",
The context cannot be null, in the _Node_ activation values are read from context.

2016-11-05 03:45 UTC, sandeshh commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    int bufferServerPort = 0;
done

2016-11-05 03:46 UTC, sandeshh commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    Server bufferServer = null;
done

2016-11-05 03:46 UTC, sandeshh commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    bufferServerPort = bindAddr.getPort();
done

2016-11-07 17:55 UTC, sandeshh commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    issContext.setBufferServerAddress(InetSocketAddress.createUnresolved("localhost", bufferServerPort));
Done. Using "localhost" to create the socket address.

2016-11-09 22:58 UTC, vrozov commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    while (tupleWait.sweep() != null) {
Should the condition be reversed?

2016-11-09 23:58 UTC, sandeshh commented on engine/src/test/java/com/datatorrent/stram/engine/GenericNodeTest.java
> +    while (tupleWait.sweep() != null) {
Yes, will change it.

2016-11-14 17:30 UTC, merged