APEXCORE-592 Return additional parameter description from properties.xml in defaultProperties for get-app-package-info command
apache/apex-core pull request #464
Opened 2017-02-06 09:10 UTC by ajaygit158

Sample data and output : 
**properties.xml**
<property>
<name>dt.application.FraudDetectDemo.operator.smaPerMerchant.windowSize
</name>
<value>30</value>
<description>Window size</description>
</property>
<property>
<name>dt.application.FraudDetectDemo.operator.movingSum.attr.APPLICATION_WINDOW_COUNT
</name>
<value>10</value>
<description>Window count for application</description>
</property>

**Output : get-app-package-info package-name**
"dt.application.FraudDetectDemo.operator.smaPerMerchant.windowSize":
{ "value": "30", "description": "Window size" }
,
"dt.application.FraudDetectDemo.operator.movingSum.attr.APPLICATION_WINDOW_COUNT":
{ "value": "10", "description": null }

2017-02-06 09:26 UTC, ajaygit158 commented
@vrozov Kindly review.

2017-02-06 19:48 UTC, vrozov commented
@sandeshh Please review. @amberarrow See if this affects documentation.

2017-02-06 23:20 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/client/DTConfiguration.java
> +  public Map<String, ValueEntry> getMap()
There is no need for getMap()

2017-02-06 23:25 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +        LOG.info("Properties: {} {} {}", key, valueEntry.value, valueEntry.description);
LOG.debug?

2017-02-07 00:15 UTC, sandeshh commented
Please see my comment in the jira.

2017-02-15 02:31 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/cli/ApexCli.java
> +        //Ignore all attribute descriptions since attributes are platform dependent and not app-package dependent.
Have you explored changing the values at the source or during load?

2017-02-26 16:03 UTC, vrozov commented on engine/src/main/java/com/datatorrent/stram/cli/ApexCli.java
> +        //Ignore all attribute descriptions since attributes are platform dependent and not app-package dependent.
@sandeshh Please see discussion in JIRA.

2017-03-07 16:38 UTC, vrozov commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +        LOG.info("Properties: {} {} {}", key, valueEntry.value, valueEntry.description);
Why is the logging necessary, especially for every Map.Entry in the Set?

2017-03-07 16:39 UTC, vrozov commented
@ajaygit158 Please address review comments, rebase to upstream/master and squash commits.

2017-03-07 19:07 UTC, ajaygit158-zz reviewed
Review comments addressed. Code rebased.

2017-03-07 19:07 UTC, ajaygit158-zz commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +        LOG.info("Properties: {} {} {}", key, valueEntry.value, valueEntry.description);
True. Removed the log

2017-03-07 19:07 UTC, ajaygit158-zz commented on engine/src/main/java/com/datatorrent/stram/client/DTConfiguration.java
> +  public Map<String, ValueEntry> getMap()
I am using it in AppPackage.java

2017-03-08 05:55 UTC, ajaygit158 commented
Jenkins Build is failing. Closing and reopening the PR.

2017-03-14 05:44 UTC, ajaygit158 commented
Jenkins Build was failing. Closing and reopening the PR.

2017-03-14 05:56 UTC, ajaygit158-zz commented
@vrozov Kindly review

2017-03-14 07:08 UTC, ajaygit158 commented
@tushargosavi Kindly review the changes

2017-03-14 23:49 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/client/DTConfiguration.java
> +  public Map<String, ValueEntry> getMap()
DTConfiguration exposes iterators, that should be used. Map is an internal representation which should not be exposed.

2017-03-15 01:34 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/client/DTConfiguration.java
>    public static class ValueEntry
Please make this private. Introduce PropertyInfo class in AppPackage, with value and description.

You can populate the description field from DtConfiguration.getDescription method

2017-03-15 10:14 UTC, ajaygit158 commented
@sandeshh Incorporated all your review comments.

2017-03-15 13:42 UTC, vrozov requested changes
squash commits.

2017-03-15 13:42 UTC, vrozov commented on engine/src/main/java/com/datatorrent/stram/client/DTConfiguration.java
> +    @JsonIgnore
Is it still necessary?

2017-03-15 13:42 UTC, vrozov commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +        PropertyInfo propertyInfo = new PropertyInfo();
It is not necessary to construct propertyInfo when `value == null`, move to line 466.

2017-03-15 13:42 UTC, vrozov commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +    private String value;
Both value and description should be final.

2017-03-15 19:09 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/cli/ApexCli.java
> +          if (entry.getKey().contains(".attr.")) {
While creating the PropertyInfo don't load the Description for attributes. So you don't need both the for loops.

2017-03-15 19:09 UTC, sandeshh commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +            defaultProperties.put(key, propertyInfo);
While creating Property make description null for attributes

2017-03-15 22:25 UTC, ajaygit158 commented on engine/src/main/java/com/datatorrent/stram/client/DTConfiguration.java
> +    @JsonIgnore
Forgot to remove. Removed this in updated PR.

2017-03-15 22:25 UTC, ajaygit158 commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +    private String value;
Changed

2017-03-15 22:26 UTC, ajaygit158 commented on engine/src/main/java/com/datatorrent/stram/client/AppPackage.java
> +        PropertyInfo propertyInfo = new PropertyInfo();
changed

2017-03-15 22:27 UTC, ajaygit158 commented on engine/src/main/java/com/datatorrent/stram/cli/ApexCli.java
> +          if (entry.getKey().contains(".attr.")) {
Updated the code for this change.

2017-03-15 23:16 UTC, sandeshh approved these changes
Please squash the commits. If @vrozov is fine will merge it.

2017-03-16 02:42 UTC, ajaygit158 commented
Build failed for non related test. Closing and Reopening PR

2017-03-16 03:16 UTC, ajaygit158 commented
Squashed the commits.

2017-03-16 03:51 UTC, vrozov approved these changes
@sandeshh Please merge.

2017-03-16 04:04 UTC, merged